title: Bleeding Edge Tech
name: ivan-placid
github_username:  ivan-placid
description: Site description goes here.

url: ""
baseurl: ""
permalink: /:categories/:title/


# Build settings
markdown: kramdown
theme: clean-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


collections:
  projects:
    output: true
    permalink: /portfolio/:title