title: Bleeding Edge Tech
name: Ivan Doh!
description: Site description goes here.
baseurl: ""
url: ""
github_username:  ivan-placid
permalink: /posts/:year/:month/:day/:title/

# Build settings
markdown: kramdown
theme: clean-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
